#!/usr/bin/env bash
set -euo pipefail

OUT_FILE="${1:-.env}"
GPG_FILE="${GPG_FILE:-secrets/secrets.env.gpg}"

tmp="$(mktemp)"
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT

echo "# Generated by scripts/gen_env.sh on $(date -Iseconds)" > "$tmp"
echo "# Do not commit this file." >> "$tmp"
echo "" >> "$tmp"

if [[ -f "$GPG_FILE" ]]; then
  # Decrypt pre-stored secret env lines into the output (expects KEY=VALUE lines).
  gpg --quiet --decrypt "$GPG_FILE" >> "$tmp"
  echo "" >> "$tmp"
fi

# Best-effort dynamic values from authenticated CLIs (no secrets printed).
if command -v aws >/dev/null 2>&1; then
  acct="$(aws sts get-caller-identity --output json 2>/dev/null | python3 -c 'import sys,json; print(json.load(sys.stdin).get("Account",""))' || true)"
  region="$(aws configure get region 2>/dev/null || true)"
  [[ -n "${acct:-}" ]] && echo "AWS_ACCOUNT_ID=\"$acct\"" >> "$tmp"
  [[ -n "${region:-}" ]] && echo "AWS_DEFAULT_REGION=\"$region\"" >> "$tmp"
fi

if command -v az >/dev/null 2>&1; then
  azout="$(az account show --output json 2>/dev/null || true)"
  if [[ -n "${azout:-}" ]]; then
    tenant="$(printf '%s' "$azout" | python3 -c 'import sys,json; print(json.load(sys.stdin).get("tenantId",""))' || true)"
    sub="$(printf '%s' "$azout" | python3 -c 'import sys,json; print(json.load(sys.stdin).get("id",""))' || true)"
    [[ -n "${tenant:-}" ]] && echo "AZURE_TENANT_ID=\"$tenant\"" >> "$tmp"
    [[ -n "${sub:-}" ]] && echo "AZURE_SUBSCRIPTION_ID=\"$sub\"" >> "$tmp"
  fi
fi

if command -v ibmcloud >/dev/null 2>&1; then
  ibmout="$(ibmcloud account show --output json 2>/dev/null || true)"
  if [[ -n "${ibmout:-}" ]]; then
    acct="$(printf '%s' "$ibmout" | python3 -c 'import sys,json; print(json.load(sys.stdin).get("account_id",""))' || true)"
    [[ -n "${acct:-}" ]] && echo "IBM_ACCOUNT_ID=\"$acct\"" >> "$tmp"
  fi
fi

mkdir -p "$(dirname "$OUT_FILE")" 2>/dev/null || true
chmod 600 "$tmp" 2>/dev/null || true
mv "$tmp" "$OUT_FILE"
echo "Wrote: $OUT_FILE"

