param(
  [string]$OutFile = (Join-Path $PSScriptRoot '..\\.env'),
  [string]$StoreFile = (Join-Path $PSScriptRoot '..\\secrets\\secrets.dpapi.json'),
  [switch]$NoDynamic
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Unprotect-Dpapi([string]$cipherText) {
  $secure = ConvertTo-SecureString -String $cipherText
  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try { return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr) }
  finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
}

function DotenvQuote([string]$value) {
  $escaped = $value -replace '\\', '\\\\'
  $escaped = $escaped -replace '\"', '\\"'
  $escaped = $escaped -replace \"`r?`n\", \"\\n\"
  return '\"' + $escaped + '\"'
}

$envMap = [ordered]@{}

if (Test-Path -LiteralPath $StoreFile) {
  $store = Get-Content -LiteralPath $StoreFile -Raw | ConvertFrom-Json
  if ($store.secrets) {
    foreach ($p in $store.secrets.PSObject.Properties) {
      $envMap[$p.Name] = (Unprotect-Dpapi $p.Value)
    }
  }
}

if (-not $NoDynamic) {
  if (Get-Command aws -ErrorAction SilentlyContinue) {
    try {
      $id = aws sts get-caller-identity --output json 2>$null | ConvertFrom-Json
      if ($id.Account -and -not $envMap.Contains('AWS_ACCOUNT_ID')) { $envMap['AWS_ACCOUNT_ID'] = [string]$id.Account }
      $region = (aws configure get region 2>$null)
      if ($region -and -not $envMap.Contains('AWS_DEFAULT_REGION')) { $envMap['AWS_DEFAULT_REGION'] = [string]$region }
    } catch {}
  }

  if (Get-Command az -ErrorAction SilentlyContinue) {
    try {
      $acct = az account show --output json 2>$null | ConvertFrom-Json
      if ($acct.tenantId -and -not $envMap.Contains('AZURE_TENANT_ID')) { $envMap['AZURE_TENANT_ID'] = [string]$acct.tenantId }
      if ($acct.id -and -not $envMap.Contains('AZURE_SUBSCRIPTION_ID')) { $envMap['AZURE_SUBSCRIPTION_ID'] = [string]$acct.id }
    } catch {}
  }

  if (Get-Command ibmcloud -ErrorAction SilentlyContinue) {
    try {
      $acct = ibmcloud account show --output json 2>$null | ConvertFrom-Json
      if ($acct.account_id -and -not $envMap.Contains('IBM_ACCOUNT_ID')) { $envMap['IBM_ACCOUNT_ID'] = [string]$acct.account_id }
    } catch {}
  }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Generated by scripts/gen_env.ps1 on $(Get-Date -Format o)")
$lines.Add("# Do not commit this file.")
$lines.Add("")

foreach ($k in ($envMap.Keys | Sort-Object)) {
  $lines.Add("$k=$(DotenvQuote ([string]$envMap[$k]))")
}

$outDir = Split-Path -Parent $OutFile
if ($outDir -and -not (Test-Path -LiteralPath $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }
$lines | Set-Content -LiteralPath $OutFile -Encoding utf8NoBOM

Write-Output "Wrote: $OutFile"
Write-Output ("Keys: " + ($envMap.Keys.Count))

