#!/usr/bin/env bash
set -euo pipefail

repo="${1:-}"
visibility="${2:-public}" # public|private

if [[ -z "$repo" ]]; then
  echo "Usage: ./export_output_to_github.sh <repo-name-or-owner/repo> [public|private]" >&2
  exit 2
fi

cd "$(dirname "$0")/output"

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI not found. Install GitHub CLI and re-run." >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "gh is not authenticated. Run: gh auth login" >&2
  exit 1
fi

if [[ ! -f .gitignore ]]; then
  cat > .gitignore <<'EOF'
.env
.env.*
node_modules/
dist/
build/
__pycache__/
*.pyc
.venv/
EOF
fi

if [[ ! -d .git ]]; then
  git init -q
fi

git add -A
git -c user.name=localAI -c user.email=localai@local commit -m "Generated by localAI" >/dev/null 2>&1 || true

if [[ "$visibility" == "private" ]]; then
  gh repo create "$repo" --source . --private --push
else
  gh repo create "$repo" --source . --public --push
fi

echo "Exported to GitHub: $repo"

