param(
  [Parameter(Mandatory = $true, Position = 0)]
  [string]$Repo,

  [ValidateSet('public', 'private')]
  [string]$Visibility = 'public'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$out = Join-Path $root 'output'
Set-Location $out

if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
  throw "gh CLI not found. Install GitHub CLI and re-run."
}

& gh auth status *> $null
if ($LASTEXITCODE -ne 0) {
  throw "gh is not authenticated. Run: gh auth login"
}

if (-not (Test-Path ".\\.gitignore")) {
@'
.env
.env.*
node_modules/
dist/
build/
__pycache__/
*.pyc
.venv/
'@ | Set-Content -Encoding utf8NoBOM ".\\.gitignore"
}

if (-not (Test-Path ".\\.git")) {
  git init | Out-Null
}

git add -A | Out-Null
git -c user.name=localAI -c user.email=localai@local commit -m "Generated by localAI" *> $null

if ($Visibility -eq 'private') {
  gh repo create $Repo --source . --private --push
} else {
  gh repo create $Repo --source . --public --push
}

Write-Output "Exported to GitHub: $Repo"

