import json
import requests
import os
import sys
import time

OLLAMA_URL = "http://localhost:11434/api/chat"
MODEL = "gemma4:26b-optimized"


def ask_gemma(system, user):
    response = requests.post(
        OLLAMA_URL,
        json={
            "model": MODEL,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "stream": False,
            "options": {
                "temperature": 1.0,
                "top_p": 0.95,
                "top_k": 64,
            },
        },
    )
    return response.json()["message"]["content"]


def run_test(test_code):
    try:
        # Run tests from the output directory so relative paths resolve correctly
        import subprocess
        result = subprocess.run(
            [sys.executable, "-c", test_code],
            cwd="output",
            capture_output=True,
            text=True,
            timeout=10
        )
        if result.returncode == 0:
            return True, None
        else:
            err = (result.stderr or "").strip()
            out = (result.stdout or "").strip()
            if err:
                return False, err
            return False, out or "test failed"
    except Exception as e:
        return False, str(e)


def strip_code_fences(text: str) -> str:
    if "```" not in text:
        return text.strip()

    parts = text.split("```")
    if len(parts) >= 3:
        candidate = parts[1]
        if "\n" in candidate:
            first, rest = candidate.split("\n", 1)
            if first.strip().isalpha() and len(first.strip()) <= 12:
                candidate = rest
        return candidate.strip()

    return text.strip()


def topo_sort_tasks(tasks):
    order_index = {t.get("id"): i for i, t in enumerate(tasks)}
    deps = {t.get("id"): list(t.get("depends_on") or []) for t in tasks if t.get("id")}
    indeg = {tid: 0 for tid in deps}
    children = {tid: [] for tid in deps}

    for tid, dlist in deps.items():
        filtered = [d for d in dlist if d in deps and d != tid]
        deps[tid] = filtered
        for d in filtered:
            indeg[tid] += 1
            children[d].append(tid)

    ready = sorted([tid for tid, v in indeg.items() if v == 0], key=lambda x: order_index.get(x, 0))
    out_ids = []

    while ready:
        tid = ready.pop(0)
        out_ids.append(tid)
        for c in children.get(tid, []):
            indeg[c] -= 1
            if indeg[c] == 0:
                ready.append(c)
                ready.sort(key=lambda x: order_index.get(x, 0))

    if len(out_ids) != len(indeg):
        return tasks

    by_id = {t.get("id"): t for t in tasks}
    sorted_tasks = [by_id[tid] for tid in out_ids if tid in by_id]
    sorted_tasks.extend([t for t in tasks if not t.get("id")])
    return sorted_tasks


def list_output_files(root="output", max_files=200):
    paths = []
    for dirpath, _, filenames in os.walk(root):
        for fn in filenames:
            rel = os.path.relpath(os.path.join(dirpath, fn), root)
            paths.append(rel)
    paths.sort()
    if len(paths) > max_files:
        return paths[:max_files] + [f"... ({len(paths) - max_files} more)"]
    return paths


def update_project_context(task, output_root="output", max_chars=4000):
    ctx_path = os.path.join(output_root, "PROJECT_CONTEXT.md")
    line = f"- {task.get('file','')} — {task.get('title','')}\n"
    prev = ""
    if os.path.exists(ctx_path):
        with open(ctx_path, "r", encoding="utf-8", errors="ignore") as f:
            prev = f.read()
    combined = (prev + line)[-max_chars:]
    with open(ctx_path, "w", encoding="utf-8") as f:
        f.write(combined)


def build_task(task, test_code, max_retries=3):
    system_prompt = """
You are a senior software engineer.
You are working inside an existing codebase generated by previous tasks.
Write complete working code for EXACTLY the single file path specified.
No stubs. No placeholders. No TODOs. Complete code only.
Return ONLY the raw code. No explanation. No markdown.
"""
    intent = ""
    if os.path.exists("compressed_intent.txt"):
        with open("compressed_intent.txt", "r", encoding="utf-8", errors="ignore") as f:
            intent = f.read().strip()

    project_context = ""
    ctx_path = os.path.join("output", "PROJECT_CONTEXT.md")
    if os.path.exists(ctx_path):
        with open(ctx_path, "r", encoding="utf-8", errors="ignore") as f:
            project_context = f.read().strip()

    output_files = ", ".join(list_output_files("output"))

    for attempt in range(max_retries):
        print(f"  Attempt {attempt + 1}...")

        code = ask_gemma(
            system_prompt,
            "App intent:\n"
            f"{intent}\n\n"
            "Existing files in output/ (for context):\n"
            f"{output_files}\n\n"
            "Completed tasks (most recent tail):\n"
            f"{project_context}\n\n"
            "Task to implement:\n"
            f"ID: {task.get('id','')}\n"
            f"Title: {task.get('title','')}\n"
            f"File: {task.get('file','')}\n"
            f"Description: {task.get('description','')}\n",
        )

        code = strip_code_fences(code)

        output_path = os.path.join("output", task["file"])
        os.makedirs(
            os.path.dirname(output_path) if os.path.dirname(output_path) else "output",
            exist_ok=True,
        )

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(code)

        passed, error = run_test(test_code)

        if passed:
            print(f"  ✓ Passed")
            update_project_context(task)
            return True
        else:
            print(f"  ✗ Failed: {error}")

    print(f"  ✗ Failed after {max_retries} attempts")
    return False


with open("tasks.json", "r") as f:
    tasks = json.load(f)

with open("tests.json", "r") as f:
    tests = json.load(f)

test_lookup = {t["task_id"]: t["test_code"] for t in tests}

os.makedirs("output", exist_ok=True)

tasks = topo_sort_tasks(tasks)

results = []
for task in tasks:
    if task.get("status") == "done":
        print(f"Skipping {task['id']} (already done)")
        continue

    print(f"\nBuilding: {task['id']} — {task['title']}")

    test_code = test_lookup.get(task["id"], "pass")
    success = build_task(task, test_code)

    task["status"] = "done" if success else "failed"
    results.append({"id": task["id"], "success": success})

    with open("tasks.json", "w") as f:
        json.dump(tasks, f, indent=2)

print("\n--- Build Complete ---")
done = sum(1 for r in results if r["success"])
print(f"{done}/{len(results)} tasks completed")
print("Check /output/ for your software")

try:
    manifest = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "model": MODEL,
        "ollama_url": OLLAMA_URL,
        "intent": open("compressed_intent.txt", "r", encoding="utf-8", errors="ignore").read().strip()
        if os.path.exists("compressed_intent.txt")
        else "",
        "tasks_total": len(tasks),
        "results": results,
        "output_files": list_output_files("output", max_files=1000),
    }
    with open(os.path.join("output", "build_manifest.json"), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
except Exception:
    pass
